### PR TITLE
feat: add botlist.space

### PR DESCRIPTION
**Pull request by geenva**

### CODE REVIEW

**Comment by alii** [comment]
LGTM, please add the comma after the object before and I'll merge this :D

**Comment by geenva** [comment]
Looks like someone forgot how to use JSON yet again...

**Comment by geenva** [comment]
Done. Sorry for the inconvenience!

**Comment by alii** [comment]
😛 could you double check where you added it

**Comment by geenva** [comment]
I'm so sorry about that. Haven't worked in JSON in quite a while.

**Comment by alii** [comment]
Perfect, thanks!

**Pull request merged**
